#!/usr/bin/python3
import sys
import psycopg2


conn = None

if len(sys.argv) < 3:
    print("Usage: ./courses-studied studentID term")
    exit(1)
student_id = sys.argv[1]
semester = sys.argv[2]

STUDENTS_QUERY = """
SELECT
    *
FROM
    students
WHERE
    id = %s
"""

COURSES_STUDIED_QUERY = """
SELECT
    subject_code,
    subject_name
FROM
    student_course_enrolments
WHERE
    student_id = %s
    AND term_code = %s
ORDER BY
    subject_code

"""

try:
    conn = psycopg2.connect("dbname=uni")
    cur = conn.cursor()

    cur.execute(STUDENTS_QUERY, [student_id])
    res = cur.fetchone()
    if res is None:
        print("No such student")
        sys.exit(0)

    cur.execute(COURSES_STUDIED_QUERY, [student_id, semester])
    subjects = cur.fetchall()
    for subject_code, subject_name in subjects:
        print(f"{subject_code} {subject_name}")

    # Print out the subjects that the given
    # student_id studied in the given term
except psycopg2.Error as err:
    print("database error: ", err)
finally:
    if conn is not None:
        conn.close()
